FROM python:3.10

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY backend/ .

EXPOSE 80

CMD python3 manage.py makemigrations &&\
    python3 manage.py migrate &&\
    python3 create_user.py &&\
    daphne -b 0.0.0.0 -p 80 backend.asgi:application