FROM node:14.21.3 AS installer

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

FROM node:14.21.3 as release

WORKDIR /app

COPY --from=installer /app /app

COPY src ./src
COPY public ./public

RUN npm run build


FROM nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/mime.types /conf/mime.types
COPY --from=release /app/build /static

EXPOSE 8080

